# Generated by Django 5.1.4 on 2026-03-17 16:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("phone", models.CharField(db_index=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("CALLED", "Called"),
                            ("NOT_ANSWERED", "Not Answered"),
                            ("INTERESTED", "Interested"),
                            ("SITE_VISIT", "Site Visit"),
                            ("WON", "Won"),
                            ("LOST", "Lost"),
                        ],
                        db_index=True,
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("FACEBOOK", "Facebook Ads"),
                            ("GOOGLE", "Google Ads"),
                            ("WEBSITE", "Website"),
                            ("MANUAL", "Manual Upload"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "next_call_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "phone_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SHA-256 hash of normalized phone",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.clientaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["client", "status"],
                        name="leads_lead_client__b5cc38_idx",
                    ),
                    models.Index(
                        fields=["client", "assigned_to"],
                        name="leads_lead_client__48083d_idx",
                    ),
                ],
                "unique_together": {("client", "phone")},
            },
        ),
    ]
