# Generated by Django 5.1.4 on 2026-03-18 06:38

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_leadbatch_lead_batch"),
    ]

    operations = [
        TrigramExtension()
    ]
