# Generated by Django 5.1.4 on 2026-03-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_trigram_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
