# Generated by Django 5.1.4 on 2026-03-18 15:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientaccount_plan_clientaccount_trial_days_and_more'),
        ('leads', '0005_lead_last_interaction_at_sitevisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField(db_index=True, help_text='When the follow-up call should happen')),
                ('note', models.TextField(blank=True, default='')),
                ('is_completed', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False, help_text='Whether the 30-min reminder email was sent')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Lead's stated budget", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='interested_flat',
            field=models.CharField(blank=True, help_text='Which flat/unit the lead is interested in', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_count',
            field=models.IntegerField(default=0, help_text='Number of times this lead has been marked lost'),
        ),
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Telecaller notes from calls'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['client', 'lost_count'], name='leads_lead_client__3868da_idx'),
        ),
        migrations.AddField(
            model_name='followupreminder',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clientaccount'),
        ),
        migrations.AddField(
            model_name='followupreminder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followupreminder',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='leads.lead'),
        ),
        migrations.AddIndex(
            model_name='followupreminder',
            index=models.Index(fields=['created_by', 'is_completed'], name='leads_follo_created_a9f055_idx'),
        ),
        migrations.AddIndex(
            model_name='followupreminder',
            index=models.Index(fields=['scheduled_at', 'email_sent'], name='leads_follo_schedul_a1947a_idx'),
        ),
    ]
