# Generated by Django 5.1.4 on 2026-03-22 11:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientaccount_geofencing_enabled_clientlocation'),
        ('leads', '0006_followupreminder_lead_budget_lead_interested_flat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followupreminder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followupreminder',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='leadbatch',
            name='checksum',
            field=models.CharField(blank=True, default='', help_text='SHA-256 checksum for integrity verification', max_length=64),
        ),
        migrations.AddField(
            model_name='leadbatch',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadbatch',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='leadbatch',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='leadbatch',
            name='mime_type',
            field=models.CharField(blank=True, default='', help_text='MIME type of uploaded file', max_length=100),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='followupreminder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LeadAssignmentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', help_text='e.g., round-robin, manual, lost-escalation', max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who performed the reassignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_changes_made', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clientaccount')),
                ('from_user', models.ForeignKey(blank=True, help_text='Previous assignee (null if first assignment)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_transferred_from', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='leads.lead')),
                ('to_user', models.ForeignKey(blank=True, help_text='New assignee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_transferred_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead', 'created_at'], name='leads_leada_lead_id_1122b8_idx'), models.Index(fields=['client', 'to_user'], name='leads_leada_client__a1f02a_idx')],
            },
        ),
    ]
