# Generated by Django 5.1.4 on 2026-03-22 11:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clientlocation_geofence_type_and_more'),
        ('leads', '0007_followupreminder_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('activity_type', models.CharField(choices=[('STATUS_CHANGE', 'Status Change'), ('CALL_LOGGED', 'Call Logged'), ('NOTE_ADDED', 'Note Added'), ('ASSIGNED', 'Lead Assigned'), ('REASSIGNED', 'Lead Reassigned'), ('SITE_VISIT_SCHEDULED', 'Site Visit Scheduled'), ('SITE_VISIT_COMPLETED', 'Site Visit Completed'), ('FOLLOW_UP_SET', 'Follow-up Reminder Set'), ('FOLLOW_UP_COMPLETED', 'Follow-up Completed'), ('ESCALATED', 'Lead Escalated'), ('IMPORTED', 'Lead Imported from CSV'), ('ARCHIVED', 'Lead Archived'), ('RESTORED', 'Lead Restored')], db_index=True, max_length=30)),
                ('title', models.CharField(help_text="Human-readable summary, e.g. 'Status changed from NEW to CALLED'", max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra context: old_status, new_status, call_duration, etc.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('client', 'phone'), ('client', 'phone_hash')},
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['client', 'created_at'], name='leads_lead_client__fd34d1_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'created_at'], name='leads_lead_status_2b0e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['client', 'source'], name='leads_lead_client__a50a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['client', 'is_deleted'], name='leads_lead_client__a98c71_idx'),
        ),
        migrations.AddField(
            model_name='activitytimeline',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clientaccount'),
        ),
        migrations.AddField(
            model_name='activitytimeline',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='activitytimeline',
            name='performed_by',
            field=models.ForeignKey(blank=True, help_text='User who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activitytimeline',
            index=models.Index(fields=['lead', 'created_at'], name='leads_activ_lead_id_be1b50_idx'),
        ),
        migrations.AddIndex(
            model_name='activitytimeline',
            index=models.Index(fields=['client', 'activity_type'], name='leads_activ_client__8c4cc0_idx'),
        ),
        migrations.AddIndex(
            model_name='activitytimeline',
            index=models.Index(fields=['performed_by', 'created_at'], name='leads_activ_perform_a1cab5_idx'),
        ),
    ]
