# Generated by Django 5.1.4 on 2026-03-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_activitytimeline_alter_lead_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='area',
            field=models.CharField(blank=True, default='', help_text='Preferred area/location of the lead', max_length=255),
        ),
    ]
