# Generated by Django 5.1.4 on 2026-03-23 15:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clientlocation_geofence_type_and_more'),
        ('leads', '0009_lead_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='field_agent',
            field=models.ForeignKey(blank=True, help_text='Assigned field agent for site visits', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_hot',
            field=models.BooleanField(db_index=True, default=False, help_text='Potential buyer flag'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clientaccount')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('client', 'name')},
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project the lead is interested in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.project'),
        ),
    ]
