# Generated by Django 5.1.4 on 2026-03-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_lead_field_agent_lead_is_hot_project_lead_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CALLED', 'Called'), ('NOT_ANSWERED', 'Not Answered'), ('INTERESTED', 'Interested'), ('SITE_VISIT', 'Site Visit'), ('WON', 'Won'), ('LOST', 'Lost'), ('INVALID_NUMBER', 'Invalid Number')], db_index=True, default='NEW', max_length=20),
        ),
    ]
