# Generated by Django 5.1.4 on 2026-04-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_add_invalid_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadbatch',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Batch source name provided during upload', max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook Ads'), ('GOOGLE', 'Google Ads'), ('WEBSITE', 'Website'), ('MANUAL', 'Manual Upload'), ('OTHER', 'Other')], default='OTHER', max_length=255),
        ),
    ]
