# Generated by Django 5.1.4 on 2026-04-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_leadbatch_name_alter_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='available_1bhk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='available_2bhk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='available_3bhk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='has_1bhk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='has_2bhk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='has_3bhk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='price_range',
            field=models.CharField(blank=True, default='', help_text='e.g. 65L – 1.2Cr', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='total_1bhk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='total_2bhk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='total_3bhk',
            field=models.IntegerField(default=0),
        ),
    ]
