# Generated by Django 5.1.4 on 2026-04-04 12:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_clientaccount_subscription_start'),
        ('leads', '0013_project_available_1bhk_project_available_2bhk_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('notif_type', models.CharField(choices=[('WON', 'Lead Won'), ('LOST', 'Lead Lost'), ('REMINDER', 'Call Reminder'), ('ASSIGNMENT', 'Lead Assigned'), ('VISIT', 'Site Visit'), ('UPLOAD', 'Leads Uploaded'), ('INFO', 'General Info')], db_index=True, default='INFO', max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clientaccount')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='leads.lead')),
                ('site_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='leads.sitevisit')),
                ('user', models.ForeignKey(help_text='The recipient of this notification', on_delete=django.db.models.deletion.CASCADE, related_name='lead_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='leads_notif_user_id_40dbbc_idx'), models.Index(fields=['client', 'user'], name='leads_notif_client__1867f8_idx')],
            },
        ),
    ]
