# Generated by Django 5.1.4 on 2026-04-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupreminder',
            name='is_push_sent',
            field=models.BooleanField(default=False, help_text='Whether the 5-min push reminder was sent'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('WON', 'Lead Won'), ('LOST', 'Lead Lost'), ('REMINDER', 'Call Reminder'), ('ASSIGNMENT', 'Lead Assigned'), ('VISIT', 'Site Visit'), ('UPLOAD', 'Leads Uploaded'), ('INFO', 'General Info'), ('BROADCAST', 'Broadcast')], db_index=True, default='INFO', max_length=20),
        ),
    ]
