# Generated by Django 5.1.4 on 2026-06-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_followupreminder_is_push_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('WON', 'Lead Won'), ('LOST', 'Lead Lost'), ('REMINDER', 'Call Reminder'), ('ASSIGNMENT', 'Lead Assigned'), ('VISIT', 'Site Visit'), ('UPLOAD', 'Leads Uploaded'), ('INFO', 'General Info'), ('BROADCAST', 'Broadcast'), ('SYSTEM', 'System'), ('SUBSCRIPTION_WARNING', 'Subscription Warning'), ('SUBSCRIPTION_EXPIRED', 'Subscription Expired')], db_index=True, default='INFO', max_length=20),
        ),
    ]
