# Generated by Django 5.1.4 on 2026-08-14 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_alter_notification_notif_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_called_at',
            field=models.DateTimeField(blank=True, help_text='When the last call was made to this lead', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_called_by',
            field=models.ForeignKey(blank=True, help_text='Who made the last call to this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_called_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CALLED', 'Called'), ('NOT_ANSWERED', 'Not Answered'), ('INTERESTED', 'Interested'), ('HIGH_PROSPECT', 'High Prospect'), ('FOLLOW_UP', 'Follow-up'), ('SITE_VISIT', 'Site Visit Scheduled'), ('VISITED', 'Site Visit Done'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost'), ('INVALID_NUMBER', 'Invalid Number')], db_index=True, default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('WON', 'Lead Won'), ('LOST', 'Lead Lost'), ('REMINDER', 'Call Reminder'), ('ASSIGNMENT', 'Lead Assigned'), ('VISIT', 'Site Visit'), ('UPLOAD', 'Leads Uploaded'), ('INFO', 'General Info'), ('BROADCAST', 'Broadcast'), ('SYSTEM', 'System'), ('SUBSCRIPTION_WARNING', 'Subscription Warning'), ('SUBSCRIPTION_EXPIRED', 'Subscription Expired'), ('AGED', 'Stale Lead Alert'), ('FOLLOW_UP', 'Follow-up Reminder')], db_index=True, default='INFO', max_length=20),
        ),
    ]
