# Generated by Django 5.1.4 on 2026-03-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='When True, the user must change their password before accessing any other API endpoint.', verbose_name='must change password'),
        ),
    ]
