# Generated by Django 5.1.4 on 2026-03-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='geofencing_exempt',
            field=models.BooleanField(default=False, help_text="If True, this specific user overrides their organization's geofencing rules (useful for global agents).", verbose_name='exempt from geofencing'),
        ),
    ]
