# Generated by Django 5.1.4 on 2026-03-22 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_geofencing_exempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notification_prefs', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('aged_lead_alerts', models.BooleanField(default=True, help_text='Notify when leads go idle beyond threshold')),
                ('duplicate_lead_alerts', models.BooleanField(default=True, help_text='Notify when CSV upload contains duplicates')),
                ('daily_performance_summary', models.BooleanField(default=True, help_text='Email summary of team performance')),
                ('site_visit_reminders', models.BooleanField(default=True, help_text='Push notification before scheduled visits')),
                ('lost_lead_notifications', models.BooleanField(default=False, help_text='Alert when lead is marked lost 4 times')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='Email used in the attempt', max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['email', 'attempted_at'], name='accounts_lo_email_687415_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password_hash', models.CharField(help_text='Hashed password (same format as auth)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Password Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
