# Generated by Django 5.1.4 on 2026-06-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_fcmdevice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
