# Generated by Django 5.1.4 on 2026-03-17 16:17

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Company Name", max_length=255)),
                (
                    "subdomain",
                    models.CharField(
                        blank=True,
                        help_text="For future tenant-specific routing",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "max_users",
                    models.IntegerField(
                        default=5, help_text="Maximum allowed employees"
                    ),
                ),
                (
                    "storage_quota_mb",
                    models.IntegerField(
                        default=1024, help_text="File storage quota in MB"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Client Account",
                "verbose_name_plural": "Client Accounts",
                "ordering": ["-created_at"],
            },
        ),
    ]
