# Generated by Django 5.1.4 on 2026-03-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='trial_days',
            field=models.IntegerField(default=14, help_text='Number of trial days'),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Subscription valid until date', null=True),
        ),
    ]
