# Generated by Django 5.1.4 on 2026-03-22 09:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientaccount_plan_clientaccount_trial_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='geofencing_enabled',
            field=models.BooleanField(default=False, help_text='Global toggle to enforce geolocation checking for employees'),
        ),
        migrations.CreateModel(
            name='ClientLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Branch Office', help_text='e.g., Main Office', max_length=150)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_meters', models.IntegerField(default=500, help_text='Permitted login radius around this coordinate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_locations', to='clients.clientaccount')),
            ],
        ),
    ]
