# Generated by Django 5.1.4 on 2026-03-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientaccount_geofencing_enabled_clientlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlocation',
            name='geofence_type',
            field=models.CharField(choices=[('CIRCLE', 'Circle (radius-based)'), ('POLYGON', 'Polygon (custom boundary)')], default='CIRCLE', help_text='CIRCLE uses lat/lng/radius. POLYGON uses polygon_coords.', max_length=10),
        ),
        migrations.AddField(
            model_name='clientlocation',
            name='polygon_coords',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of {lat, lng} points defining the polygon boundary'),
        ),
        migrations.AlterField(
            model_name='clientlocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='clientlocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
