# Generated by Django 5.1.4 on 2026-03-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clientlocation_geofence_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='daily_field_agent_target',
            field=models.IntegerField(default=8, help_text='Daily visit target per field agent'),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='daily_telecaller_target',
            field=models.IntegerField(default=100, help_text='Daily call target per telecaller'),
        ),
    ]
