# Generated by Django 5.1.4 on 2026-04-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clientaccount_daily_field_agent_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='subscription_start',
            field=models.DateField(blank=True, help_text='Subscription/trial start date', null=True),
        ),
    ]
