# Generated by Django 5.1.4 on 2026-04-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_clientaccount_subscription_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='force_logout_until',
            field=models.DateTimeField(blank=True, help_text='Forces all employees to log in again if their token was issued before this timestamp.', null=True),
        ),
    ]
